version: '3'
services:
  api:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3333:3333'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
